#pragma once

// TODO probably wrong order, possibly wrong underlying type
enum class ClientFrameStage : int {
	FRAME_SIMULATE = 0,
	FRAME_NET_PRE_PROCESS_NETWORKING,
	FRAME_NET_POST_PROCESS_NETWORKING,
	FRAME_NET_BLOCKING_LOAD_SPAWN_GROUP,
	FRAME_NET_UPDATE_START,
	FRAME_NET_UPDATE_PREDICTION,
	FRAME_NET_UPDATE_POSTDATAUPDATE_START,
	FRAME_NET_UPDATE_POSTDATAUPDATE_END,
	FRAME_NET_UPDATE_FULL_UPDATE_RECEIVED,
	FRAME_NET_UPDATE_END,
};