#pragma once

// NOLINTNEXTLINE(performance-enum-size)
enum class ClientFrameStage : int {
    FRAME_UNDEFINED = -1,
    FRAME_NET_START = 0,
    FRAME_SIMULATE_START = 1,
    FRAME_UNK1 = 2,
    FRAME_NET_UPDATE_START = 3,
    FRAME_NET_UPDATE_POSTDATAUPDATE_START = 4,
    FRAME_NET_UPDATE_POSTDATAUPDATE_END = 5,
    FRAME_NET_UPDATE_END = 6,
    FRAME_START = 7, // unsure...
    FRAME_SIMULATE_END = 8
};
