#pragma once

// NOLINTNEXTLINE(performance-enum-size)
enum class ClientFrameStage : int {
    FRAME_UNDEFINED = -1,
    FRAME_NET_START = 0,
    FRAME_SIMULATE_START = 1,
    FRAME_NET_UPDATE_START = 2,
    FRAME_NET_UPDATE_PREPROCESS = 3,
    FRAME_NET_FULL_FRAME_UPDATE_ON_REMOVE = 4,
    FRAME_NET_UPDATE_POSTDATAUPDATE_START = 5,
    FRAME_NET_UPDATE_POSTDATAUPDATE_END = 6,
    FRAME_NET_UPDATE_END = 7,
    FRAME_SIMULATE_END = 8
};
