name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        distro: ["ubuntu:latest", "ubuntu:rolling", "debian:unstable", "debian:testing", "archlinux:latest", "cachyos/cachyos", "fedora:latest", "opensuse/tumbleweed"]
      fail-fast: false
    runs-on: ubuntu-latest
    container: ${{ matrix.distro }}
    steps:
      - if: matrix.distro == 'ubuntu:latest'
        name: Setup dependencies
        run: |
          apt-get update
          apt-get install -y git cmake make build-essential libvulkan-dev libx11-dev libxext-dev gcc-14 g++-14
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 999
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 999
      - if: matrix.distro == 'ubuntu:rolling' || matrix.distro == 'debian:unstable' || matrix.distro == 'debian:testing'
        name: Setup dependencies
        run: |
          apt-get update
          apt-get install -y git cmake make build-essential libvulkan-dev libx11-dev libxext-dev
      - if: matrix.distro == 'archlinux:latest' || matrix.distro == 'cachyos/cachyos'
        name: Setup dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel cmake git vulkan-icd-loader vulkan-headers libx11 libxext
      - if: matrix.distro == 'fedora:latest'
        name: Setup dependencies
        run: |
          dnf update -y
          dnf install -y git cmake make gcc-c++ vulkan-loader-devel vulkan-headers libXext-devel
      - if: matrix.distro == 'opensuse/tumbleweed'
        name: Setup dependencies
        run: |
          zypper refresh
          zypper install -y git cmake make gcc-c++ binutils-devel vulkan-devel libXext-devel freetype2-devel

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: ./Build.sh
