name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        distro: ["ubuntu:22.04", "ubuntu:23.04", "ubuntu:23.10", "debian:latest", "debian:unstable", "debian:testing", "dockerscripts/linuxmint:mate", "archlinux:latest", "manjarolinux/base:latest", "fedora:latest"]
      fail-fast: false
    runs-on: ubuntu-latest
    container: ${{ matrix.distro }}
    steps:
      - if: startsWith(matrix.distro, 'ubuntu:') || matrix.distro == 'dockerscripts/linuxmint:mate' || matrix.distro == 'debian:latest'
        name: Setup dependencies
        run: |
          apt-get update
          apt-get install -y curl git cmake make build-essential libsdl2-dev libvulkan-dev
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gcc@13
      - if: matrix.distro == 'debian:unstable' || matrix.distro == 'debian:testing'
        name: Setup dependencies
        run: |
          apt-get update
          apt-get install -y git cmake make build-essential libsdl2-dev libvulkan-dev
      - if: matrix.distro == 'archlinux:latest' || matrix.distro == 'manjarolinux/base:latest'
        name: Setup dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel cmake git sdl2 vulkan-icd-loader vulkan-headers
      - if: matrix.distro == 'fedora:latest'
        name: Setup dependencies
        run: |
          dnf update -y
          dnf install -y git cmake make gcc-c++ SDL2-devel vulkan-loader-devel vulkan-headers libXext-devel

      - name: Install SDL3
        run: |
          git clone https://github.com/libsdl-org/SDL
          cd SDL
          cmake -S . -B build
          cmake --build build
          cmake --install build

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - if: startsWith(matrix.distro, 'ubuntu:') || matrix.distro == 'dockerscripts/linuxmint:mate' || matrix.distro == 'debian:latest'
        name: Build
        run: CC=gcc-13 CXX=g++-13 ./Build.sh

      - if: "!(startsWith(matrix.distro, 'ubuntu:') || matrix.distro == 'dockerscripts/linuxmint:mate') || matrix.distro == 'debian:latest'"
        name: Build
        run: ./Build.sh

      - name: Distro name for artifact
        id: distro_name
        run: |
          CONTAINER_NAME=${{ matrix.distro }}
          . /etc/os-release
          TMP_OUTPUT=$(echo "name=$NAME" | sed "s/\// /g")
          if [ "$CONTAINER_NAME" == "debian:unstable" ]; then
            echo "$TMP_OUTPUT unstable" >> "$GITHUB_OUTPUT"
          elif [ "$CONTAINER_NAME" == "debian:testing" ]; then
            echo "$TMP_OUTPUT testing" >> "$GITHUB_OUTPUT"
          else
            echo $TMP_OUTPUT >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.distro_name.outputs.name }}
          path: |
            Build/*.so
