name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        distro: ["ubuntu:22.04", "ubuntu:23.04", "ubuntu:23.10", "debian:unstable", "debian:testing", "dockerscripts/linuxmint:mate", "archlinux:latest", "manjarolinux/base:latest", "fedora:latest"]
      fail-fast: false
    runs-on: ubuntu-latest
    container: ${{ matrix.distro }}
    steps:
      - if: matrix.distro == 'ubuntu:22.04' || matrix.distro == 'ubuntu:23.04' || matrix.distro == 'dockerscripts/linuxmint:mate' || matrix.distro == 'debian:latest'
        name: Setup dependencies
        run: |
          apt update
          apt install -y software-properties-common
          add-apt-repository -y ppa:ubuntu-toolchain-r/test
          apt update
          apt install -y git cmake make build-essential libvulkan-dev libx11-dev libxext-dev gcc-13 g++-13
      - if: matrix.distro == 'debian:unstable' || matrix.distro == 'debian:testing' || matrix.distro == 'ubuntu:23.10'
        name: Setup dependencies
        run: |
          apt-get update
          apt-get install -y git cmake make build-essential libvulkan-dev libx11-dev libxext-dev
      - if: matrix.distro == 'archlinux:latest' || matrix.distro == 'manjarolinux/base:latest'
        name: Setup dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel cmake git vulkan-icd-loader vulkan-headers libx11 libxext
      - if: matrix.distro == 'fedora:latest'
        name: Setup dependencies
        run: |
          dnf update -y
          dnf install -y git cmake make gcc-c++ vulkan-loader-devel vulkan-headers libXext-devel

      - name: Install SDL3
        run: | # Official build instructions from https://wiki.libsdl.org/SDL3/Installation
          git clone https://github.com/libsdl-org/SDL
          cd SDL
          git checkout SDL-prerelease-3.0.0-2926-gaaf54b09a # Found by calling SDL_GetRevision (https://wiki.libsdl.org/SDL3/SDL_GetRevision)
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel
          cmake --install . --config Release

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - if: matrix.distro == 'ubuntu:22.04' || matrix.distro == 'ubuntu:23.04' || matrix.distro == 'dockerscripts/linuxmint:mate' || matrix.distro == 'debian:latest'
        name: Build
        run: CC=gcc-13 CXX=g++-13 ./Build.sh

      - if: "!(matrix.distro == 'ubuntu:22.04' || matrix.distro == 'ubuntu:23.04' || matrix.distro == 'dockerscripts/linuxmint:mate' || matrix.distro == 'debian:latest')"
        name: Build
        run: ./Build.sh

      - name: Distro name for artifact
        id: distro_name
        run: |
          CONTAINER_NAME=${{ matrix.distro }}
          . /etc/os-release
          TMP_OUTPUT=$(echo "name=$PRETTY_NAME" | tr ':/' '  ')
          echo $TMP_OUTPUT >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.distro_name.outputs.name }}
          path: |
            Build/*.so
