name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        distro: ["ubuntu:latest",  "debian:unstable", "debian:testing", "archlinux:latest", "fedora:latest"]
      fail-fast: false
    runs-on: ubuntu-latest
    container: ${{ matrix.distro }}
    steps:
      - if: matrix.distro == 'ubuntu:latest'
        name: Setup dependencies
        run: |
          apt update
          apt install -y software-properties-common
          add-apt-repository -y ppa:ubuntu-toolchain-r/test
          apt update
          apt install -y git cmake make build-essential libvulkan-dev libx11-dev libxext-dev gcc-13 g++-13
      - if: matrix.distro == 'debian:unstable' || matrix.distro == 'debian:testing'
        name: Setup dependencies
        run: |
          apt-get update
          apt-get install -y git cmake make build-essential libvulkan-dev libx11-dev libxext-dev
      - if: matrix.distro == 'archlinux:latest'
        name: Setup dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel cmake git vulkan-icd-loader vulkan-headers libx11 libxext
      - if: matrix.distro == 'fedora:latest'
        name: Setup dependencies
        run: |
          dnf update -y
          dnf install -y git cmake make gcc-c++ vulkan-loader-devel vulkan-headers libXext-devel

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: ./Build.sh
